stages:
2    - checkov
3#variables: 
4#  ALLOWFAILURE: "true" #True for AutoDevOps compatibility
5#  AWS_DEFAULT_REGION: us-west-1
6#  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
7#  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
8
9#before_script:
10 # - rm -rf .terraform
11 # - export TF_LOG=TRACE
12 # - terraform --version
13 # - opa version
14 # - echo "Do your deploy here"
15 # - cd $CI_PROJECT_DIR
16 # - export http_proxy="http://xxx.145.xx.x:xxxx"
17 # - export https_proxy="$http_proxy"
18 # - export no_proxy="127.0.0.1, localhost, .companyxxx.com, .companyxxx.net"
19 # - export HTTP_PROXY="$http_proxy"
20 # - export HTTPS_PROXY="$http_proxy"
21 # - export NO_PROXY="$no_proxy"
22 # - opa version
23 # - export AWS_ACCESS_KEY_ID
24 # - export AWS_SECRET_ACCESS_KEY
25 # - export AWS_SESSION_TOKEN
26 # - terraform init
27
28checkov:
29  stage: checkov
30#  allow_failure: $ALLOWFAILURE
31  allow_failure: true
32  image:
33    name: bridgecrew/checkov:latest
34    entrypoint:
35      - '/usr/bin/env'
36      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
37  rules:
38    - if: $SAST_DISABLED
39      when: never
40    - if: $CI_COMMIT_BRANCH
41      exists:
42      - '**/*.yml'
43      - '**/*.yaml'
44      - '**/*.json'
45      - '**/*.template'
46      - '**/*.tf'      
47      - '**/serverless.yml'
48      - '**/serverless.yaml'
49  script:
50    # Use `script` to emulate `tty` for colored output.
51    # - checkov -d . -o junitxml | tee checkov.test.xml
52     - script -q -c 'checkov -d . ; echo $? > CKVEXIT'
53    # - exit $(cat CKVEXIT)
54    # - touch checkov.xml
55     - checkov -d . -o junitxml | tee checkov.xml
56     - exit $(cat CKVEXIT)
57  tags:
58      - gitlab-runner
59  artifacts:
60    when: always
61    reports:
62      junit: "checkov.xml"
63#       junit: "**/*.checkov.xml"
64    paths:
65      - "checkov.xml"
66#       - "**/*.checkov.test.xml"
